# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MeCab DF
#' @param str Text
#' @param tagger_opt Tagger
mecab_df <- function(str, tagger_opt) {
    .Call(`_ymattuR_mecab_df`, str, tagger_opt)
}

